### ISSUE TITLE
UmVtb3ZlIHNlbnNpdGl2ZSBjb250ZW50IHRvIGRlc2Vuc2l0aXpl

### ISSUE THREAD

**Issue by SilvaQ** [gheyret/UyghurOCR#1]
Q29uc2lkZXJpbmcgdGhlIGRvbWVzdGljIHVzZXJzIG9mIHRoaXMgc29mdHdhcmUsIHRoZXkgYXJlIHZlcnkgZWFnZXIgdG8gZGVzZW5zaXRpemUgYWxsIGF1eGlsaWFyeSBzYW1wbGUgaW5mb3JtYXRpb24gY2FycmllZCBieSB0aGUgc29mdHdhcmUgYW5kIGRlbGV0ZSBzZW5zaXRpdmUgY29udGVudOOAggpQbGVhc2UgY29uc2lkZXIgdGhlIHRyYWdlZHkgb2Ygc29tZSB1bndpdHRpbmcgdXNlcnMgYWNjaWRlbnRhbGx5IGVhdGluZyBzdGVhbWVkIGJ1bnMuIFRoYW5rIHlvdSB2ZXJ5IG11Y2jjgII=

> base64...

**Comment by gheyret** [comment]
bWlzYWwgcWlsaW5naGFuIHJlc2ltbGVybmkgZGVtZWtjaGlzbXVzaXo/

**Comment by SilvaQ** [comment]
> bWlzYWwgcWlsaW5naGFuIHJlc2ltbGVybmkgZGVtZWtjaGlzbXVzaXo/

SGUgZSBzaHVuZGFxLgpTaXpuaW5nIGdoZXlyZXRAZ21haWwuY29tIGlsaGV0aW5naXpnZSB1Y2h1ciBxYWxkdXJkdW0

**Comment by SilvaQ** [comment]
eger bolghudek bolsa issue ni yuyiwetken bolsaq ,rehmet.
