### ISSUE TITLE
1.4 neshiri win11 x64 te kozghulixi normal amas

### ISSUE THREAD

**Issue by rustam255786** [gheyret/UyghurOCR#2]
yahximusiz, bugun bu sestimini win11 x64 te iqip sinap bakkantim towendikidek hatalik qikiwaldi 
![image](https://user-images.githubusercontent.com/71540796/176958242-6131a8fd-d4c9-4779-a144-3bd038b57385.png)

**Comment by gheyret** [comment]
Salam,
Tesseract "Microsoft Visual C++ Redistributable" gha beqinidiken. shunga towendiki ulinishtin 64 bitliqqa mas kelidighanni ornitip andin UyghurOCR ni ijra qilip korup baqamsiz?

https://support.microsoft.com/en-us/topic/the-latest-supported-visual-c-downloads-2647da03-1eea-4433-9aff-95f26a218cc0

Biwasite ulinishi:
https://aka.ms/vs/17/release/vc_redist.x64.exe
